module Helper

 def self.output
   [{"snippet"=>{"publishedAt"=>"2017-01-13T22:16:37.000Z", "channelId"=>"UCVguiojKA6iobcySMJ5boNA", "title"=>"My 2016 Annual Review", "description"=>"It's that time again! Every year I dedicate a couple days to reviewing my entire year, personally and professionally so I can reflect on the health of my business, ...", "thumbnails"=>{"url"=>"https://i.ytimg.com/vi/5JQzbc2MgQY/hqdefault.jpg", "width"=>480, "height"=>360}, "channelTitle"=>"Brad Hussey", "liveBroadcastContent"=>"none"}}, {"snippet"=>{"publishedAt"=>"2017-01-06T21:30:48.000Z", "channelId"=>"UCVguiojKA6iobcySMJ5boNA", "title"=>"Kicking off 2017! (plus DIY selfie stick)", "description"=>"Happy 2017 everyone! Let's make this year YOUR year! Just a quick update with what you can expect from me first thing this year... 1) Remodeling my new ...", "thumbnails"=>{"url"=>"https://i.ytimg.com/vi/xHRCTxEFWPc/hqdefault.jpg", "width"=>480, "height"=>360}, "channelTitle"=>"Brad Hussey", "liveBroadcastContent"=>"none"}}, {"snippet"=>{"publishedAt"=>"2016-12-18T16:00:01.000Z", "channelId"=>"UCVguiojKA6iobcySMJ5boNA", "title"=>"[#14] Now what do I do? (Learn Sass)", "description"=>"DOWNLOAD THE FINAL COURSE FILES: https://app.convertkit.com/landing_pages/136231?v=6 THE SASS COURSE by Brad Hussey & Code College Thanks ...", "thumbnails"=>{"url"=>"https://i.ytimg.com/vi/N15dOfyM1ko/hqdefault.jpg", "width"=>480, "height"=>360}, "channelTitle"=>"Brad Hussey", "liveBroadcastContent"=>"none"}}]
 end

 def self.input
   [{"kind"=>"youtube#searchResult", "etag"=>"\"uQc-MPTsstrHkQcRXL3IWLmeNsM/wXzEGe9-O3zcTlSSG6YS6Lp-eio\"", "id"=>{"kind"=>"youtube#video", "videoId"=>"5JQzbc2MgQY"}, "snippet"=>{"publishedAt"=>"2017-01-13T22:16:37.000Z", "channelId"=>"UCVguiojKA6iobcySMJ5boNA", "title"=>"My 2016 Annual Review", "description"=>"It's that time again! Every year I dedicate a couple days to reviewing my entire year, personally and professionally so I can reflect on the health of my business, ...", "thumbnails"=>{"default"=>{"url"=>"https://i.ytimg.com/vi/5JQzbc2MgQY/default.jpg", "width"=>120, "height"=>90}, "medium"=>{"url"=>"https://i.ytimg.com/vi/5JQzbc2MgQY/mqdefault.jpg", "width"=>320, "height"=>180}, "high"=>{"url"=>"https://i.ytimg.com/vi/5JQzbc2MgQY/hqdefault.jpg", "width"=>480, "height"=>360}}, "channelTitle"=>"Brad Hussey", "liveBroadcastContent"=>"none"}}, {"kind"=>"youtube#searchResult", "etag"=>"\"uQc-MPTsstrHkQcRXL3IWLmeNsM/shPHiSJnFOq3NKeQMEFWq2tD5OM\"", "id"=>{"kind"=>"youtube#video", "videoId"=>"xHRCTxEFWPc"}, "snippet"=>{"publishedAt"=>"2017-01-06T21:30:48.000Z", "channelId"=>"UCVguiojKA6iobcySMJ5boNA", "title"=>"Kicking off 2017! (plus DIY selfie stick)", "description"=>"Happy 2017 everyone! Let's make this year YOUR year! Just a quick update with what you can expect from me first thing this year... 1) Remodeling my new ...", "thumbnails"=>{"default"=>{"url"=>"https://i.ytimg.com/vi/xHRCTxEFWPc/default.jpg", "width"=>120, "height"=>90}, "medium"=>{"url"=>"https://i.ytimg.com/vi/xHRCTxEFWPc/mqdefault.jpg", "width"=>320, "height"=>180}, "high"=>{"url"=>"https://i.ytimg.com/vi/xHRCTxEFWPc/hqdefault.jpg", "width"=>480, "height"=>360}}, "channelTitle"=>"Brad Hussey", "liveBroadcastContent"=>"none"}}, {"kind"=>"youtube#searchResult", "etag"=>"\"uQc-MPTsstrHkQcRXL3IWLmeNsM/mamf-kJiOq-mShXwNgoqCqACnMI\"", "id"=>{"kind"=>"youtube#video", "videoId"=>"N15dOfyM1ko"}, "snippet"=>{"publishedAt"=>"2016-12-18T16:00:01.000Z", "channelId"=>"UCVguiojKA6iobcySMJ5boNA", "title"=>"[#14] Now what do I do? (Learn Sass)", "description"=>"DOWNLOAD THE FINAL COURSE FILES: https://app.convertkit.com/landing_pages/136231?v=6 THE SASS COURSE by Brad Hussey & Code College Thanks ...", "thumbnails"=>{"default"=>{"url"=>"https://i.ytimg.com/vi/N15dOfyM1ko/default.jpg", "width"=>120, "height"=>90}, "medium"=>{"url"=>"https://i.ytimg.com/vi/N15dOfyM1ko/mqdefault.jpg", "width"=>320, "height"=>180}, "high"=>{"url"=>"https://i.ytimg.com/vi/N15dOfyM1ko/hqdefault.jpg", "width"=>480, "height"=>360}}, "channelTitle"=>"Brad Hussey", "liveBroadcastContent"=>"none"}}]
 end

end
